export const SYSTEM_CATEGORIES = [
  { name: 'Образование' },
  { name: 'Работа' },
  { name: 'Хобби' },
  { name: 'Здоровье' },
  { name: 'Спорт' },
  { name: 'Развлечения' },
  { name: 'Путешествие' },
  { name: 'Покупки' },
  { name: 'Документы' },
  { name: 'Встречи' },
  { name: 'Быт' },
  { name: 'Отношения' },
  { name: 'Красота' },
] as const;
