POST http://localhost:3000/api/account/register HTTP/1.1
Content-Type: application/json

{
  "email": "1132233495@pfur.ru",
  "password": "izvara32"
}

###

POST http://localhost:3000/api/account/confirm-email HTTP/1.1
Content-Type: application/json

{
  "token": "5e13ca8636c2422797a17fb8e256136ad76ad654684f75f93f23105aefe1f3bb"
}

###

POST http://localhost:3000/api/account/login HTTP/1.1
Content-Type: application/json

{
  "email": "1132233495@pfur.ru",
  "password": "izvara32"
}


###

GET http://localhost:3000/api/account/login HTTP/1.1

###

GET http://localhost:3000/api/account HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTAzY2EzNS02NWQ3LTQ4OGYtYWI5Zi1jZTAwMmFjYTdlMWQiLCJlbWFpbCI6IjExMzIyMzM0OTVAcGZ1ci5ydSIsImV4cCI6MTc2NTAxOTA5MCwiaWF0IjoxNzY1MDExODkwfQ.UToD47OYKtFd17SnGhba58ypuU-ug88D8lt_RjsSzvo

###

GET http://localhost:3000/api/account/ba2137d3-e0a6-49a4-803b-29206f8657cd HTTP/1.1
Authorization: Bearer .


###

PATCH http://localhost:3000/api/account HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYTIxMzdkMy1lMGE2LTQ5YTQtODAzYi0yOTIwNmY4NjU3Y2QiLCJlbWFpbCI6Im9sZWdfb3Jsb3ZfMjAwNUBtYWlsLnJ1IiwiZXhwIjoxNzY0OTU5MjEwLCJpYXQiOjE3NjQ5NTIwMTB9.a_ugXYkAltF79-kwYzX-Q8lQ5FL7D1_Ik17n5RmYKVQ
Content-Type: application/json

{
  "name": "Олег"
}

###

DELETE http://localhost:3000/api/account HTTP/1.1
Authorization: Bearer ..

###

GET http://localhost:3000/api/account/exit HTTP/1.1
Authorization: Bearer ..
Cookie: refresh_token=;

###

GET http://localhost:3000/api/account/logout HTTP/1.1
Authorization: Bearer ..
